### ISSUE TITLE
Issue while executing the script in cmd prompt - Archiving Content to CSV

### ISSUE THREAD

**Issue by urspalani** [fbsamples/workplace-platform-samples#113]
Hi, 
I was using 'Archiving Content to CSV'([link](https://github.com/fbsamples/workplace-platform-samples/tree/main/SupportScripts/Python/DownloadGroupFeed)) scripts provided and followed the steps provided in the same page, but still got the error as attached.
Requesting the team for kind attention.
![Error](https://user-images.githubusercontent.com/32320057/185153623-f72c1184-d633-4212-a4c0-f5295260e195.png)

**Comment by TK48** [comment]
Hi,
Error message, <!DOCTYPE html> is HTML document type declaration but this Python code do not use HTML.
Please compare your code and original sample code.

**Comment by xarain81** [comment]
I had a similar issue.
inspect your .py code and ensure it does not have html embedded within. 
Alternative is the copy / paste the .py code from github.

**Comment by urspalani** [comment]
Hi , thanks for the replies.
Actually later I realized I didn't copy the code directly from the link and instead downloaded , because of that got some html code.
Now I did tried the Py code and it had some error in closing brackets and fixed it , but struck with the attached error now.

**Comment by urspalani** [comment]
Hi , thanks for the replies.
Actually later I realized I didn't copy the code directly from the link and instead downloaded , because of that got some html code.
Now I did tried the Py code and it had some error in closing brackets and fixed it , but struck with the attached error now
![error](https://user-images.githubusercontent.com/32320057/187122451-a039dfdd-b681-441d-a0d7-a546cafe2f70.jpg)
.

**Comment by urspalani** [comment]
Does anyone used the code and executed successfully without any error, can help to share that version pls.

**Comment by urspalani** [comment]
Hi

**Comment by xarain81** [comment]
Hi @urspalani 
I have fixed the code above and it worked for me. 
Please ensure the following:
1. You need to run using Python 2.7 (I read that you made some code changes, suggest you re-start using the original code)
2. There are 3 areas you need to fix
     a.  Line 45 - Change from ("%S") to ("%s")  [i.e. change of case]
     b. Line 81 - Change from ("%S") to ("%s")  [i.e. change of case]
     c. Line 131 - Change from ("%Y-%m-%d %H:%M:%S") to ("%Y-%m-%d %H-%M-%S")   [i.e. remove the colon ]

Let me know if this resolves the issue. I will initiate a pull request to update the code.

**Comment by urspalani** [comment]
Hi @xarain81 ,
I used the original code and replaced the token and for #2(a & b) it was with small case only, so I left that and I changed only c.
But still struck with error , refer to attached screen shot.
And I am using Python 3.8.6 , will that be issue ?
![Screenshot 2022-09-01 120747](https://user-images.githubusercontent.com/32320057/187829626-2b82d775-abda-47fd-89a0-7f2a70456fff.jpg)

**Comment by xarain81** [comment]
You need to run as Python 2.7.
https://www.python.org/download/releases/2.7/
The sample code here will not work on Python 3.x

**Comment by urspalani** [comment]
Ok Installed 2.7 and struck with the attached error.
![Uploading Screenshot 2022-09-01 165749.jpg…]()

**Comment by urspalani** [comment]
Ok Installed 2.7 and struck with the attached error.
![Screenshot 2022-09-01 165749](https://user-images.githubusercontent.com/32320057/187875597-6289381a-e22d-491c-9f20-c90a8d68821d.jpg)

**Comment by urspalani** [comment]
Hi @xarain81  , any update on this ?

**Comment by TK48** [comment]
Do you install requests module?

**Comment by urspalani** [comment]
Thanks @TK48 , installed the required module and there is some error on the group id.
Do I need to add the group id and name in the code , line 124 ?

for group in getGroups():
    feed = getFeed(group["id"], group["name"])

    # Create a new CSV named after the timestamp / group id / group name, to ensure uniqueness
    csv_filename = SINCE.strftime("%Y-%m-%d %H-%M-%S") + " " + group["id"] + " " + strip(group["name"]) + ".csv"


![Screenshot 2022-09-06 170709](https://user-images.githubusercontent.com/32320057/188595165-9cb3d748-5e9d-46cf-8960-c397d82129ef.jpg)

**Comment by TK48** [comment]
The format depends on the platform. How about back to original?
a. Line 45 - Change from ("%s") to ("%S") [i.e. change of case]
b. Line 81 - Change from ("%s") to ("%S") [i.e. change of case]

**Comment by urspalani** [comment]
Finally seems working , it generated few csv files but not sure what basis it extracted.
Can I understand if I can give parameter on groups I need to extract and also the days ?

**Comment by TK48** [comment]
Line 15: DAYS = 14 is option. 
If you set DAYS = 1, you can get posts which was created 1 day before only.

This script looks new posts in each group within the option days and if it found new posts, it makes a CSV file for each group.

**Comment by urspalani** [comment]
ya but is there any filter we can use for group , because we have around 8K+ group and it will not be feasible if it downloads the data for all group and we get request to download only for few groups for longer period.
And also looks like this code extracts only closed group data , when I run it only extracted for 40+ group where we have more groups in total.

**Comment by TK48** [comment]
I found the cause. The code does not handle paginated results and query parameters well. I modified the code. Please copy new one and test it.

**Comment by rwicks001** [comment]
@urspalani Did you manage to test the new code?

**Comment by TK48** [comment]
Yes, I uploaded new code.
I changed parameters description and if-condition.

Line 41 and other lines related "params"
(old)  params += "&amp;limit=" + DEFAULT_LIMIT
(new) params += "&limit=" + DEFAULT_LIMIT

Line 107
(old) if json.dumps('"paging"') in result_json:
(new) if "next" in result_json["paging"]:

**Comment by urspalani** [comment]
Thanks @TK48 , is there any parameter input required now with the new code ? got this error now 
![Screenshot 2022-09-12 125203](https://user-images.githubusercontent.com/32320057/189576327-c8276fdd-2d65-4c79-bfec-b7c0e1077463.jpg)

**Comment by TK48** [comment]
That is the same error you had.
Could you test to change from ("%s") to ("%S")?

**Comment by urspalani** [comment]
I think we have more data ,it is asking to limit

![image](https://user-images.githubusercontent.com/32320057/189584745-828572d3-c980-424f-ae82-54aabe64c0e8.png)

**Comment by TK48** [comment]
This sample mentioned it potentially has an overflow on line 70 and 71. This program keeps data in memory and would overflow if data size is huge.
How about change DAYS in line 15? The default value is 14. You can try to reduce this number and test it.

Otherwise it needs to rewrite the code to avoid the overflow. For example, this starts writing CSV after reading all, but it can be avoided by reading and writing one by one.

**Comment by urspalani** [comment]
Actually I had just put '1' day only , because I know we have lot of group and it will take time.
I think need your help to re write the code or if we have the parameter to input the group id , it will be much helper.

**Comment by TK48** [comment]
Another parameter, Line 22: DEFAULT_LIMIT = "100"
You can set small number. It would be helpful.

**Comment by urspalani** [comment]
There is diff error now, pls see attached.

[Error_12092022.txt](https://github.com/fbsamples/workplace-platform-samples/files/9557494/Error_12092022.txt)

**Comment by urspalani** [comment]
Checking here again , possible to get the email id of the one who post and also total shares of each post ?
