### ISSUE TITLE
require('dotenv').load() gives TypeError: require(...).load is not a function error

### ISSUE THREAD

**Issue by himadlakha** [fbsamples/workplace-platform-samples#115]
https://github.com/fbsamples/workplace-platform-samples/blob/bcae5261ea227f2a20e946f1e417ca6e5dc1d0c4/SampleIntegrations/SampleWebhooks/NodeJS/BasicWebhooksExample/app.js#L18

require('dotenv').load() gives TypeError: require(...).load is not a function error

replacing 'load' with 'config' fixes the issue

**Comment by connortreacy** [comment]
Fixed in commit 2d07351
