### ISSUE TITLE
post 'see more' button erase text format

### ISSUE THREAD

**Issue by artyacel** [fbsamples/workplace-platform-samples#127]
My text is split in two div which erase the format I've applied on it. 
Half of the sentence is visible in bold while refreshing but when I click on the 'see more' button the rest of it appears without the bold format applied. 
In source code, the bold is applied on the full text.
Yet when look on the CSS the text is randomly splitted in two div. Can you tell me how to fix that ? So that the full text will be included in  the same div ?

**Comment by NewAlexandria** [comment]
copy the content out, reformat it in an external edit, and paste it back in fresh (overwriting all of the existing content)
