### ISSUE TITLE
Unable to Create a Group Post

### ISSUE THREAD

**Issue by daniel-statsig** [fbsamples/workplace-platform-samples#139]
I have every single permission enabled on my Workplace bot, but I am unable to create a Group Post. This was working fine yesterday.

Request:
```
curl 'https://graph.facebook.com/{{group_id}}/feed' --header 'Content-Type: application/json' --header 'Authorization: Bearer ACCESS_TOKEN' --data '{
	"message": "hello"
}'
```

Response
```
{
    "error": {
        "code": 1,
        "message": "An unknown error occurred"
    }
}
```

**Comment by daniel-statsig** [comment]
@Antiklesys any help you could provide here would be greatly appreciated

**Comment by Antiklesys** [comment]
I recommend you try regenerating the access token and validating the syntax. Also please open a support ticket via Workplace if that doesn’t solve the problem.

**Comment by daniel-statsig** [comment]
Looks like this was fixed on the FB side. It just started working again. Thanks for the help
