### ISSUE TITLE
Code errors

### ISSUE THREAD

**Issue by othernick** [fbsamples/workplace-platform-samples#23]
I came across a couple of errors in the code and accompanying notes for this sample:

1. Contrary to the accompanying notes, the code uses the `cron` module rather than `node-cron` which has no `CronJob` object. Perhaps the notes could mention that this module needs to be installed separately, or include a dependency to it in `package.json` .
2. On line 44 of `clock.js` the url makes no sense. Either the notes should say that `.env` should be modified such that `TARGET_GROUP=/<group_id>/` or line 44 should be changed to include the slashes: `url: '/' + TARGET_GROUP +'feed`.

Nick Oates

**Comment by connortreacy** [comment]
Thanks for the issue reports @othernick! Fixes incoming.

**Comment by connortreacy** [comment]
Fixed in c31bdfe, 3284be0 and 36cadaa
