### ISSUE TITLE
AccountManagement drops user/s

### ISSUE THREAD

**Issue by samj** [fbsamples/workplace-platform-samples#24]
1 user of 18k was quietly dropped by scim_agent/scim_sdk:

3500 / 18484
3600 / 18484
3699 / 18484
3799 / 18484

**Comment by samj** [comment]
Manually creating a request returns 99 itemsPerPage for that page only, so it seems this is an API issue.

**Comment by samj** [comment]
Offending user is sequence # 3666 for domain dxc (when I set startIndex to 3667 the itemsPerPage returns to 100 from 99).

**Comment by jcsacto** [comment]
Did you happen to figure how to modify the code to skip these bad data situations by chance?  I tracked mine down to #1255 of #2700.  The user doesn't seem to exist in the normal UI either so not sure how to tackle it from the data side.   Any help appreciated. Thanks!

**Comment by jcsacto** [comment]
Just an FYI, this was caused by a bad record on the FB side...their support team had to go in and remove the phantom record that was causing this crash for me.  FYI
