### ISSUE TITLE
Error during export

### ISSUE THREAD

**Issue by sandralouis** [fbsamples/workplace-platform-samples#25]
Hi all,

I downloaded and ran the export function
python scim_agent.py -e Export20171012.csv <access_token> <scim_url>

But I am getting the error shown below:
Exporting users to: Export20171012.csv
Traceback (most recent call last):
  File "scim_agent.py", line 250, in <module>
    func_arg[sys.argv[1]](sys.argv[2], sys.argv[3], sys.argv[4])
  File "scim_agent.py", line 130, in exportUsers
    userCollection = scim_sdk.getUsers(scim_url, access_token, 1, userCollection)
  File "D:\G_DRIVE\WPFB\PYTHON\SAN\ORIGINAL_WPFB_FILES\scim_sdk.py", line 151, in getUsers
    totalResults = result_json[FIELD_TOTAL_RESULTS]
KeyError: 'totalResults'

Any idea what may have caused this?

**Comment by eduardogomes** [comment]
@sandralouis let me know if you are still  having this behavior

**Comment by eduardogomes** [comment]
We've not heard back from you on this issue in a while. I am going to close it. Please respond to this message if you'd like to continue the conversation.
