### ISSUE TITLE
[DownloadGroupFeed]Japanese Character can't be recognised

### ISSUE THREAD

**Issue by zoomyanagida** [fbsamples/workplace-platform-samples#27]
I downloaded and ran download.py in "DownloadGroupFeed" project.
But I found the Japanese character named group can't be recognised.

The following message is displayed.

--
Traceback (most recent call last):
  File "download2.py", line 129, in <module>
    row = [item["id"], item["permalink_url"], item["created_time"], item["updated_time"], item["from"]["name"], item["from"]["id"], item["message"].decode("utf-8").strip(), item["link"], item["likes"]["summary"]["total_count"], item["comments"]["summary"]["total_count"]]
  File "C:\Python27\lib\encodings\utf_8.py", line 16, in decode
    return codecs.utf_8_decode(input, errors, True)
UnicodeEncodeError: 'ascii' codec can't encode characters in position 0-13: ordinal not in range(128)
--
How should I fix this?

I confirmed that the English named group can be downloaded.
I ran this on Japanese Windows10 OS.

FYI, I found two another Japanese environment issues.
1. 
--
Traceback (most recent call last):
  File "download2.py", line 111, in <module>
    for group in getGroups():
  File "download2.py", line 77, in getGroups
    params = "?fields=feed.since(" + SINCE.strftime("%s") + ").limit(1),name,updated_time&amp;"
ValueError: Invalid format string
--

I changed
 SINCE.strftime("%s") 
to
 SINCE.strftime("%S")

s->"S"
 
This happens on line 42 too.

2.
--
Traceback (most recent call last):
  File "download2.py", line 121, in <module>
    with open(csv_filename, "wb") as csvfile:
IOError: [Errno 22] invalid mode ('wb') or filename: u'2017-11-23 17:02:03 2094457190639666 FW Test Forum.csv'
--

I changed 
 csv_filename = SINCE.strftime("%Y-%m-%d %H:%M:%S") 
to 
 csv_filename = SINCE.strftime("%Y-%m-%d %H_%M_%S") 
on line 115.

":" can't be used in the file name on Windows OS.

**Comment by zoomyanagida** [comment]
I'm sorry. I found the solution.

On line130, I change 
"item["message"].decode("utf-8").strip()"
to
"item["message"].encode("utf-8").strip()"
(decode -> encode)

After that, I could get the Japanese messages.

Thank you for your cooperation.

**Comment by connortreacy** [comment]
Great catch @zoomyanagida! Would you be willing to submit a pull request to this repo so that everyone benefits from the fix?
