### ISSUE TITLE
Group Feed Download Not Paging Properly

### ISSUE THREAD

**Issue by jcsacto** [fbsamples/workplace-platform-samples#29]
The group feed only returns 25 records max I believe.  Even if I set the DEFAULT_LIMIT to 25, it's still not pulling all the data and doesn't appear to be paging properly.  I have tried to debug it myself but cannot seem to figure it out.  Any help would be greatly appreciated.  

Cheers!
Jon

**Comment by Jackpohare** [comment]
I'm no expert and just about to try pulling an RSS feed and pushing to a group, but if you give some further details maybe I can try to help - e.g. where is your RSS feed coming from - it sounds like inability to get more than 25 is more to do with feed-read on the feed you are reading that fb....

**Comment by jcsacto** [comment]
Thanks for the response! We finally figured out how to get the data to paginate using alternate syntax such as: 

 if "paging" in result_json and "next" in result_json["paging"]:
        feed.extend(getFeed(group, name, nextUrl=result_json["paging"]["next"]))

Thanks again for replying!
