### ISSUE TITLE
Shockingly bad examples

### ISSUE THREAD

**Issue by tabinnorway** [fbsamples/workplace-platform-samples#30]
I am appalled that a company of this size, with a commercial product you are trying to sell to companies, publish SHOCKINGLY bad examples. Seriously, is there not a single competent person anywhere in this organization?

Take the AccountManagement examples. Atrocious.

1/ They don't compile in any version of Python newer than 2.7, that's bad but not terrible
2/ OK, so they rely on request - now, that won't install on Windows using pip, and it is also entirely unnecessary, for goodness sake, we are talking about such simple stuff as http get here.
3/ They rely on a module csv_header, this is (at least for those of us who haven't spent a decade around python) nowhere to be found

Have you people never heard about complete, and runnable examples? Seriously! This is so bad!

**Comment by tabinnorway** [comment]
Sorry, I am the moron - long night :-)

**Comment by connortreacy** [comment]
Thanks for sharing your feedback, and for following up. 

For the benefit of anyone else reading this, could you share what exactly tripped you up, and how you resolved it? You may not be the only person who found this confusing, and I'd be happy to add your learnings to the README to help others.
