### ISSUE TITLE
Is facebook workplace supports rich cards in chat bot messaging?

### ISSUE THREAD

**Issue by SatyaPavanKumar** [fbsamples/workplace-platform-samples#32]
![capture](https://user-images.githubusercontent.com/32288442/38015957-1ef91350-328b-11e8-9b85-67525ddd0e0d.GIF)
we buit custom integration bot . we hooked up integration details like app id , app secret, token etc., to facebook messenger channel in bot framework using azure. we are able to send and receive messges in workplace chat for the chat bot we created. We also wrote the code for rich cards (Thumb nail card , adaptive card, hero card etc.,)  to display in workplace chat. But rich card(s) is not getting displayed. Is facebook workplace supports rich cards to shown in chat bot messaging?Attached an image for reference of thumbnail image not showing in chat bot messaging.
Bot Code Developed in  C# .NET

**Comment by connortreacy** [comment]
Hi @SatyaPavanKumar, thanks for your question. 

This isn't a good channel for asking general support questions. Please take a look at our documentation here: https://developers.facebook.com/docs/workplace/integrations/custom-integrations/bots

And if you still have questions, consider joining our Workplace Developers community on Workplace to get help from a community of other developers: https://fb.me/g/1nDCCN08i/UtYAqpQM
