### ISSUE TITLE
How to get serverURL and validationToken for bot integration.

### ISSUE THREAD

**Issue by imdineshgrewal** [fbsamples/workplace-platform-samples#36]
Hi,

For configuration file, from where to get 'serverURL' and 'validationToken' for bot integration in workplace.?

**Comment by eduardogomes** [comment]
@imdineshgrewal which sample are you referring to?

**Comment by imdineshgrewal** [comment]
@eduardogomes Expense-bot!!

**Comment by eduardogomes** [comment]
@imdineshgrewal Thanks for bringing this up, this config file is deprecated [by environment variables](https://github.com/fbsamples/workplace-platform-samples/blob/16852521fca6da344ed53c50e43d036ee6b9a0d1/ExpenseBot/app.js#L33). 
SERVER_URL must be set as your execution environment host (as in https://hostname) and VERIFY_TOKEN is your private string used to verify the webhook subscription

**Comment by imdineshgrewal** [comment]
Hi @eduardogomes , Thanks for the explanation. really helpful. Also, I have one more question related to the webhooks. Please have a look at the below URL :

**Comment by eduardogomes** [comment]
What is your execution environment? The url must be internet public available and use HTTPs.

**Comment by eduardogomes** [comment]
@imdineshgrewal just checking in if you could review your code. I will be closing this issue tomorrow.

**Comment by eduardogomes** [comment]
Closing out this issue, please get in touch if necessary
