### ISSUE TITLE
Not able to update account records using python scripts provided

### ISSUE THREAD

**Issue by imlight** [fbsamples/workplace-platform-samples#43]
Hello , 

I have recently landed on your page as we are investigating a proper way to update workplace account information for our org. 

We started experimenting with the the scripts you have provided here. 

With below CSV file , we are getting error as Bad request ..

cat upload.csv

Email,First Name,Last Name,Job Title,Department,Phone Number,Location,Locale,Manager Email
user101@bunnings.com.au,user101,user101,Title,Department,,Location,en_US,

Error 

python scim_agent.py -c upload.csv $ACCESS_TOKEN
validating...
---> Valid File <---
Creating users...
Creating user user101@example.com
400:Bad Request
Updating managers...
==========START ERRORS==========
Failed to create user with email user101@example.com
==========END ERRORS==========

Can you suggest if we are doing anything wrong ? ( We are providing actual accesstoken in the command line )

Any help is appreciable

**Comment by imlight** [comment]
I do see , upload.csv file format has changed in 15 days ago , doesn't that have to change the actual code ??
Not sure , just guessing.

**Comment by imlight** [comment]
Format what workplace is providing is little different for upload.csv

**Comment by imlight** [comment]
Email | First Name | Last Name | Job Title | Department | Division | Organization | Phone Number | Location | Manager Email | Start Date   (YYYY-MM-DD) |   |   |   |  
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
stacy@foxfabricsglobal.com | Stacy | Kumar | Marketing Manager | Business Marketing | EMEA Sales and Marketing | Fox Fabrics EMEA | +1 990-677-7417 | Paris - Building 10 | lucy@foxfabricsglobal.com | ######## |   |   |   |   |   |  
leslie@foxfabricsglobal.com | Leslie | Chen | HR Director | Factory Personnel | APAC Talent Team | Fox Fabrics APAC | +1 999-551-2240 Ext 12345 | Singapore - Merlion Tower | kelly@foxfabricsglobal.com | ######## |   |   |   |   |   |  
  |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |

**Comment by Antiklesys** [comment]
This should now be fixed with https://github.com/fbsamples/workplace-platform-samples/commit/1f9fe7fac26823e0112cd18e2a577e8d71adb85a
