### ISSUE TITLE
Script throws an error when updating only one record or the last record

### ISSUE THREAD

**Issue by Antiklesys** [fbsamples/workplace-platform-samples#55]
The script is throwing the following errors when it is being run to update just a few records (e.g. the excel file has only one NewEmail populated or two).
When the excel file contains only one NewEmail record to update it throws the following error message:

```
ConvertFrom-Json : Cannot bind argument to parameter 'InputObject' because it is null.
At C:\changeBulkEmail.ps1:111 char:47
+ ...            $msg = ($_.ErrorDetails.Message | ConvertFrom-Json).Errors ...
+                                                  ~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidData: (:) [ConvertFrom-Json], ParameterBindingValidationException
    + FullyQualifiedErrorId : ParameterArgumentValidationErrorNullNotAllowed,Microsoft.PowerShell.Commands.ConvertFromJsonCommand

Cannot index into a null array.
At C:\changeBulkEmail.ps1:111 char:13
+             $msg = ($_.ErrorDetails.Message | ConvertFrom-Json).Error ...
+             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : NullArray
```

When there are two NewEmail records to update instead it correctly processes the update of the first one and then throws the same error as before when it tries to update the second one.

It seems the line creating the issue is:

The line creating the issue is:

`$msg = ($_.ErrorDetails.Message | ConvertFrom-Json).Errors[0].description`

Changing it to: 

`$msg = ($_.ErrorDetails.Message).Errors.description`

resolves these errors.

**Comment by panreel** [comment]
@Antiklesys i tried to repro but with no luck (input file with 1 row), can you share with me a sample file? 
![image](https://user-images.githubusercontent.com/811834/71364740-61418b00-259d-11ea-9ba0-6bd9bf63e4f1.png)

**Comment by Antiklesys** [comment]
Hi,

The error is not in the code processing the lines but in the error handler.
I submitted 3 pull requests to fix it in different files :)
Have a look at those and let me know :)

**Comment by panreel** [comment]
How do I generate an error? :) Changing username of non existent users or using non authorized tokens, which should be most common problems, fall back gracefully. Thanks.

**Comment by panreel** [comment]
#61 should solve it. @Antiklesys, can you please double check? Thanks! Looks OSX and Win manage PowerShell errors with different object structures, trying to use a common baseline.

**Comment by Antiklesys** [comment]
Confirmed working @panreel ! Closing this :)
