### ISSUE TITLE
Can't update startdate field

### ISSUE THREAD

**Issue by scottgRYN** [fbsamples/workplace-platform-samples#62]
Using the provided scripts, I can export user data no problem.  Importing/updating data, I can't update the start date field.

I download the data just fine with "Python.exe scim_agent.py -e download.csv"; my process reads that data, updates it from my HR system by updating supervisor and start date fields, and writes the data to a new CSV file Updates.csv.  I then attempt to update workplace by processing the updated .csv file:

Python.exe scim_agent.py -u updates.csv
validating...
---> Valid File <---
Updating users...
Updating user user1@mydomain.com
400:Bad Request
...

Updating user user476@mydomain.com
400:Bad Request
Updating managers...
Updating user user275@mydomain.com
200:OK
Updating user user 108@mydomain.com
200:OK
...
Updating user user3@mydomain.com
200:OK

The first pass fails, which is only updating the start date, as all other data is exactly as exported from Workplace.  The second pass succeeds, which is just updating the supervisor's ID.

Note that while the exported data for start date is in Unix date format, the validation phase of the script bombs out if the date is not passed back in in YYYY-MM-DD format; Workplace central support acknowledges that this is the correct way to pass it back in, and that is what I'm doing. 

Any advice on getting the script to successfully update the start date?

Thanks, all!

**Comment by scottgRYN** [comment]
Confirming that if I remove all non-required fields, (eg timezone through cost center),  the update happens fine -- response 200:OK.  When I add back the start date field, it bombs with a 400:Bad Request.

**Comment by Antiklesys** [comment]
This should now be fixed with https://github.com/fbsamples/workplace-platform-samples/commit/1f9fe7fac26823e0112cd18e2a577e8d71adb85a
