### ISSUE TITLE
ActiveUsers Script error

### ISSUE THREAD

**Issue by FunctionOne** [fbsamples/workplace-platform-samples#63]
As requested by Nico Cinefra:

When I run the script I am getting error:
![structure](https://user-images.githubusercontent.com/61024719/74465992-265d2480-4e75-11ea-9a24-07fb6a1cc2da.PNG)
![powershell2](https://user-images.githubusercontent.com/61024719/74465995-26f5bb00-4e75-11ea-98f8-0bbc1faaa943.png)

**Comment by panreel** [comment]
@FunctionOne can you please check permissions for access token? The `activateInBulk` script requires  at least "Manage Accounts" permissions and returned error means the access token you passed doesn't have the right set permissions. Can you please go to the Custom Integration page, try to regenerate an access token with the permissions above and ensure there are no chars missing in the accessToken.js file when copy-pasting? Also please check that the integration is active and not disabled on Workplace.

If still doesn't work, recommendation to reach out to Workplace support team by logging a ticket via Contact Support form from your Admin Panel and include integration App ID for further debugging. Ask the team to look at logs to confirm everything is properly set on our end.

**Comment by FunctionOne** [comment]
I've granted everything before start to run the script, then I was in doubt about accesstoken and I renewed:
[cid:5b804038-c278-4d71-9e1c-71c2e7ee26cf]'ve

[cid:4b887e25-d76b-491a-aeff-f3cbb6bddb8f]

[cid:3c0b654d-720a-49ea-bd9d-3b8bb5c4375e]
________________________________
[cid:a01047f7-5653-463c-b0d2-1ce3351f03c8]

[cid:e6e1b4e0-747b-478a-9f35-1cc82ce54ec1]De: Nico <notifications@github.com>
Enviado: domingo, 16 de fevereiro de 2020 17:18
Para: fbsamples/workplace-platform-samples <workplace-platform-samples@noreply.github.com>
Cc: Flávia Gomes <flavia.gomes@functionone.com.br>; Mention <mention@noreply.github.com>
Assunto: Re: [fbsamples/workplace-platform-samples] ActiveUsers Script error (#63)


@FunctionOne<https://github.com/FunctionOne> can you please check permissions for access token? The activateInBulk script requires at least "Manage Accounts" permissions and returned error means the access token you passed doesn't have the right set permissions. Can you please go to the Custom Integration page, try to regenerate an access token with the permissions above and ensure there are no chars missing in the accessToken.js file when copy-pasting? Also please check that the integration is active and not disabled on Workplace.

If still doesn't work, recommendation to reach out to Workplace support team by logging a ticket via Contact Support form from your Admin Panel and include integration App ID for further debugging. Ask the team to look at logs to confirm everything is properly set on our end.

**Comment by Antiklesys** [comment]
Can you please try by changing script line #58 from:

`$fbuser = Invoke-RestMethod -Method PUT -URI ("https://www.workplace.com/scim/v1/Users/" + $uid) -Headers @{Authorization = "Bearer " + $global:token} -UserAgent "WorkplaceScript/ActivateInBulk" -ContentType "application/json" -Body $body`

to:

`$fbuser = Invoke-RestMethod -Method PUT -URI ("https://www.facebook.com/scim/v1/Users/" + $uid) -Headers @{Authorization = "Bearer " + $global:token} -UserAgent "WorkplaceScript/ActivateInBulk" -ContentType "application/json" -Body $body`

and check if you still get an error?

**Comment by FunctionOne** [comment]
It worked!!, but seems code is exactly the same.. I didn't get the error..
before and after the correction of the script.
Thank you very much!!

[cid:d29499e1-25ab-4cf7-a27e-c655aa29cbc2]

________________________________
De: Antiklesys <notifications@github.com>
Enviado: terça-feira, 18 de fevereiro de 2020 11:28
Para: fbsamples/workplace-platform-samples <workplace-platform-samples@noreply.github.com>
Cc: Flávia Gomes <flavia.gomes@functionone.com.br>; Mention <mention@noreply.github.com>
Assunto: Re: [fbsamples/workplace-platform-samples] ActiveUsers Script error (#63)


Can you please try by changing script line #58<https://github.com/fbsamples/workplace-platform-samples/pull/58> from:

$fbuser = Invoke-RestMethod -Method PUT -URI ("https://www.workplace.com/scim/v1/Users/" + $uid) -Headers @{Authorization = "Bearer " + $global:token} -UserAgent "WorkplaceScript/ActivateInBulk" -ContentType "application/json" -Body $body

to:

$fbuser = Invoke-RestMethod -Method PUT -URI ("https://www.facebook.com/scim/v1/Users/" + $uid) -Headers @{Authorization = "Bearer " + $global:token} -UserAgent "WorkplaceScript/ActivateInBulk" -ContentType "application/json" -Body $body

and check if you still get an error?

**Comment by FunctionOne** [comment]
I compared the codes, instead of call workplace.com we should call facebook.
Thank you guys very much!!!

________________________________
De: Antiklesys <notifications@github.com>
Enviado: terça-feira, 18 de fevereiro de 2020 11:28
Para: fbsamples/workplace-platform-samples <workplace-platform-samples@noreply.github.com>
Cc: Flávia Gomes <flavia.gomes@functionone.com.br>; Mention <mention@noreply.github.com>
Assunto: Re: [fbsamples/workplace-platform-samples] ActiveUsers Script error (#63)


Can you please try by changing script line #58<https://github.com/fbsamples/workplace-platform-samples/pull/58> from:

$fbuser = Invoke-RestMethod -Method PUT -URI ("https://www.workplace.com/scim/v1/Users/" + $uid) -Headers @{Authorization = "Bearer " + $global:token} -UserAgent "WorkplaceScript/ActivateInBulk" -ContentType "application/json" -Body $body

to:

$fbuser = Invoke-RestMethod -Method PUT -URI ("https://www.facebook.com/scim/v1/Users/" + $uid) -Headers @{Authorization = "Bearer " + $global:token} -UserAgent "WorkplaceScript/ActivateInBulk" -ContentType "application/json" -Body $body

and check if you still get an error?

**Comment by Antiklesys** [comment]
Closed by switching endpoint in code from workplace.com to facebook.com. 
Internal fixes in progress for workplace.com endpoint
