### ISSUE TITLE
KO (400): BadRequest - Error en el servidor remoto: (400) Solicitud incorrecta.

### ISSUE THREAD

**Issue by matiasdangelook** [fbsamples/workplace-platform-samples#79]
Dear, 
Thank you for sharing the script here!

I'm receiving this error message:
KO (400): BadRequest - Error en el servidor remoto: (400) Solicitud incorrecta.

I think it can't find the remote site.

Any suggest?
Thanks!

**Comment by Antiklesys** [comment]
@matiasdangelook can you please specify which is the script you are using when you are receiving this error message?
